// Decompiled with JetBrains decompiler
// Type: Sandbox.Game.Gui.MyNotificationSingletons
// Assembly: Sandbox.Game, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null
// MVID: 343E1F2F-C9E5-4CAA-B3CC-F9D203DAE0A8
// Assembly location: D:\Files\library_development\lib_se\Sandbox.Game.dll

namespace Sandbox.Game.Gui
{
  public enum MyNotificationSingletons
  {
    DisabledWeaponsAndTools,
    HideHints,
    HelpHint,
    GameOverload,
    MultiplayerDisabled,
    WeaponDisabledInWorldSettings,
    SuitEnergyLow,
    SuitEnergyCritical,
    MissingComponent,
    ScreenHint,
    WorldLoaded,
    RespawnShipWarning,
    BuildingOnRespawnShipWarning,
    ClientCannotSave,
    CannotSave,
    WheelNotPlaced,
    ObstructingBlockDuringMerge,
    AccessDenied,
    CopyPasteBlockNotAvailable,
    CopyPasteFloatingObjectNotAvailable,
    CopyPasteAsteoridObstructed,
    TextPanelReadOnly,
    GameplayOptions,
    IncompleteGrid,
    AdminMenuNotAvailable,
    CopySucceeded,
    CopyFailed,
    PasteFailed,
    CutPermissionFailed,
    ManipulatingDoorFailed,
    HeadNotPlaced,
    HeadAlreadyExists,
    LimitsNoFaction,
    PlayerDemotedNone,
    PlayerDemotedScripter,
    PlayerDemotedModerator,
    PlayerDemotedSpaceMaster,
    PlayerPromotedScripter,
    PlayerPromotedModerator,
    PlayerPromotedSpaceMaster,
    PlayerPromotedAdmin,
    BlueprintScriptsRemoved,
    GridReachedPhysicalLimit,
    LimitsGridSize,
    LimitsPerBlockType,
    LimitsPlayer,
    LimitsPCU,
    ConnectionProblem,
    DeletePermissionFailed,
    BlockNotResearched,
    MissingDLC,
    BuildPlannerEmpty,
    WithdrawSuccessful,
    WithdrawFailed,
    DepositSuccessful,
    DepositFailed,
    PutToProductionSuccessful,
    PutToProductionFailed,
    BuildPlannerCapacityReached,
    BuildPlannerComponentsAdded,
    DamageTurnedOff,
    GridIsImmune,
  }
}
